### ISSUE TITLE
Add Psi Support

### ISSUE THREAD

**Issue by chris-chambers** [sbbm/llvm#8]
This is a tracking issue for psi support.  Robust predication support is going to be needed to handle the peculiarities of Minecraft/SBBM.

To get there, we need:
- [ ] Add Psi Instruction #9
- [ ] Add PsiElimination pass (at first, as an SBBM-only pass) #10
- [ ] Write a new if-conversion pass that runs before register allocation and uses psi instructions to perform predication. #11
